openapi: 3.1.0

info:
  title: Ticker Feed Schemas
  version: 1.0.0
  description: Schema definitions for ticker feed data types

paths:
  /ticker/{instrument}/{delay}:
    get:
      summary: Get ticker feed
      description: |
        Get real-time ticker data for a single instrument or combination.
        
        For combinations, mark price is the quantity-weighted sum of mark prices of leg instruments.
        Best bid/ask for combinations represent top levels of a virtual combination order book.
      operationId: getTicker
      parameters:
        - name: instrument
          in: path
          required: true
          description: |
            For single instruments: instrument name (e.g. "BTC-PERPETUAL")
            For combinations: format [<instrument_name>:<quantity>,<instrument_name>:<quantity>,...]
            Must have 2-4 distinct legs for combinations.
          schema:
            type: string
          examples:
            single:
              value: BTC-PERPETUAL
              summary: Single instrument
            combination:
              value: "[BTC-30MAY25-93000-C:-1,BTC-30MAY25-80000-C:1]"
              summary: Combination with two legs
        - name: delay
          in: path
          required: true
          description: Minimum interval between feeds
          schema:
            $ref: '#/components/schemas/Delay'
      responses:
        '200':
          description: Ticker data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TickerResponse'

components:
  schemas:
    Delay:
      type: string
      description: Minimum interval between feeds
      enum:
        - 100ms
        - 200ms
        - 500ms
        - 1000ms
        - 5000ms
        - 60000ms
        - raw
      example: 100ms
    
    TickerResponse:
      type: object
      required:
        - channel_name
        - notification
      properties:
        channel_name:
          type: string
          description: Channel name as in subscription
          pattern: ^ticker\..+\.(100ms|200ms|500ms|1000ms|5000ms|60000ms|raw)$
          example: "ticker.BTC-PERPETUAL.100ms"
        notification:
          $ref: '#/components/schemas/TickerData'
    
    TickerData:
      type: object
      required:
        - mark_price
        - mark_timestamp
      properties:
        best_bid_price:
          type: number
          nullable: true
          description: Price of the best (highest) bid in the orderbook, or null if empty
          example: 47240
        best_bid_amount:
          type: number
          nullable: true
          description: Size of best bid, or null if orderbook is empty
          example: 0.4
        best_ask_price:
          type: number
          nullable: true
          description: Price of best (lowest) ask in the orderbook, or null if empty
          example: 47260
        best_ask_amount:
          type: number
          nullable: true
          description: Size of best ask, or null if orderbook is empty
          example: 1
        last_price:
          type: number
          nullable: true
          description: Price of last trade, or null if no trades registered. Not included for combinations.
          example: 47250
        mark_price:
          type: number
          description: Current mark price
          example: 47238.64143906124
        mark_timestamp:
          type: number
          description: Unix timestamp when the price was marked
          example: 946684800
        iv:
          type: number
          description: Implied volatility calculated at time of marking. Only included for options, not combinations.
          example: 0.65
        delta:
          type: number
          description: Delta calculated at time of marking. Not included for combinations.
          example: 1
        index:
          type: number
          description: Index price at time of marking
          example: 47230
        forward:
          type: number
          description: Forward price at time of marking. Only included for options.
          example: 47235
        volume_24h:
          type: number
          description: Total volume traded over the last 24 hours. Not included for combinations.
          example: 1250.5
        value_24h:
          type: number
          description: Total value traded over the last 24 hours. Not included for combinations.
          example: 59048750
        low_price_24h:
          type: number
          description: Lowest price in the last 24 hours. Not included for combinations.
          example: 46500
        high_price_24h:
          type: number
          description: Highest price in the last 24 hours. Not included for combinations.
          example: 47800
        change_24h:
          type: number
          nullable: true
          description: Difference in price between first and last trades in last 24h, null if no trades. Not included for combinations.
          example: 740
        collar_low:
          type: number
          description: Current price collar low (checks new asks)
          example: 42000
        collar_high:
          type: number
          description: Current price collar high (checks new bids)
          example: 52000
        open_interest:
          type: number
          description: Total number of outstanding unsettled contracts. Not included for combinations.
          example: 123.456
        funding_rate:
          type: number
          description: Current rate at which long position pays and short position earns. Only included for perpetuals.
          example: 0.0001
        funding_mark:
          type: number
          description: Funding value of a single contract long position since last settlement. Only included for perpetuals.
          example: 0.05
        realised_funding_24h:
          type: number
          description: Total funding accumulated for a single contract long position over the last 24 hours. Only included for perpetuals.
          example: 1.2
        average_funding_rate_24h:
          type: number
          description: Average funding rate for the last 24 hours. Only included for perpetuals.
          example: 0.00012
