/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountSummary {
    /// Total unrealised profit or loss.
    #[serde(rename = "unrealised_pnl")]
    pub unrealised_pnl: f64,
    /// Total margin based on cash holdings.
    #[serde(rename = "cash_collateral")]
    pub cash_collateral: f64,
    /// Total margin from unrealised P&L and cash holdings.
    #[serde(rename = "margin")]
    pub margin: f64,
    /// Required margin based on current position.
    #[serde(rename = "required_margin")]
    pub required_margin: f64,
    /// Difference between margin and required margin.
    #[serde(rename = "remaining_margin")]
    pub remaining_margin: f64,
    /// Realised profit or loss in current session.
    #[serde(rename = "session_realised_pnl")]
    pub session_realised_pnl: f64,
    /// List of cash holdings, for each relevant currency, and how they contribute to margin.
    #[serde(rename = "cash")]
    pub cash: Vec<models::AccountSummaryCashInner>,
}

impl AccountSummary {
    pub fn new(
        unrealised_pnl: f64,
        cash_collateral: f64,
        margin: f64,
        required_margin: f64,
        remaining_margin: f64,
        session_realised_pnl: f64,
        cash: Vec<models::AccountSummaryCashInner>,
    ) -> AccountSummary {
        AccountSummary {
            unrealised_pnl,
            cash_collateral,
            margin,
            required_margin,
            remaining_margin,
            session_realised_pnl,
            cash,
        }
    }
}
