/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Account : Channel-specific content
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Account {}

impl Account {
    /// Channel-specific content
    pub fn new() -> Account {
        Account {}
    }
}
