/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountConfig {
    /// Unique account name.
    #[serde(rename = "name")]
    pub name: String,
    /// Enable portfolio margin for this account.  Can only be set to `true` is portfolio margin is allowed for the current customer.
    #[serde(rename = "portfolio_margin")]
    pub portfolio_margin: bool,
}

impl AccountConfig {
    pub fn new(name: String, portfolio_margin: bool) -> AccountConfig {
        AccountConfig {
            name,
            portfolio_margin,
        }
    }
}
