/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllInstrumentsParams {
    /// Start time (Unix timestamp) defaults to `time_high` - 3 days.
    #[serde(rename = "time_low", skip_serializing_if = "Option::is_none")]
    pub time_low: Option<f64>,
    /// End time (Unix timestamp) defaults to `now`.
    #[serde(rename = "time_high", skip_serializing_if = "Option::is_none")]
    pub time_high: Option<f64>,
}

impl AllInstrumentsParams {
    pub fn new() -> AllInstrumentsParams {
        AllInstrumentsParams {
            time_low: None,
            time_high: None,
        }
    }
}
