/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiKeyConfig : API key config
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyConfig {
    /// Key nickname to be displayed in the front end.
    #[serde(rename = "nickname")]
    pub nickname: String,
    /// Account number of the default account for this key.
    #[serde(rename = "default_account_number")]
    pub default_account_number: String,
    /// List of account permissions for this key.
    #[serde(rename = "permissions")]
    pub permissions: Vec<models::ApiKeyConfigPermissionsInner>,
    /// Notification preferences per category
    #[serde(rename = "notifications", skip_serializing_if = "Option::is_none")]
    pub notifications:
        Option<std::collections::HashMap<String, models::NotificationPreferencesApiKeyValue>>,
    /// If `true` this API key is active, i.e. can be used to access the API.
    #[serde(rename = "active")]
    pub active: bool,
    /// Whitelisted IP addresses.  If this list is not empty, the API key can only be used from one of the addresses on the list.  Each list item is either a single string that contains a specific IP address, or an array of exactly two strings that define a whitelisted range of IP addresses (range ends included). Strings must be valid representations of IPv4 or IPv6 addresses. Special addresses (broadcast, loopback, multicast etc.) are not allowed. The addresses must be public IPs as seen by our servers.  You can specify a maximum of 10 addresses.
    #[serde(rename = "ip_whitelist", skip_serializing_if = "Option::is_none")]
    pub ip_whitelist: Option<Vec<models::ApiKeyConfigIpWhitelistInner>>,
}

impl ApiKeyConfig {
    /// API key config
    pub fn new(
        nickname: String,
        default_account_number: String,
        permissions: Vec<models::ApiKeyConfigPermissionsInner>,
        active: bool,
    ) -> ApiKeyConfig {
        ApiKeyConfig {
            nickname,
            default_account_number,
            permissions,
            notifications: None,
            active,
            ip_whitelist: None,
        }
    }
}
