/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiKeyConfigIpWhitelistInner {
    String(String),
    Array(Vec<String>),
}

impl Default for ApiKeyConfigIpWhitelistInner {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
