/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyConfigPermissionsInner {
    /// Account number.
    #[serde(rename = "account_number")]
    pub account_number: String,
    /// Permission to view this account when logged in with this key.
    #[serde(rename = "may_view")]
    pub may_view: bool,
    /// Permission to trade in this account when logged in with this key.
    #[serde(rename = "may_trade")]
    pub may_trade: bool,
    /// Permission to withdraw assets from this account when logged in with this key.
    #[serde(rename = "may_withdraw")]
    pub may_withdraw: bool,
    /// Permission to receive account notifications when logged in with this key.
    #[serde(rename = "receive_notifications")]
    pub receive_notifications: bool,
}

impl ApiKeyConfigPermissionsInner {
    pub fn new(
        account_number: String,
        may_view: bool,
        may_trade: bool,
        may_withdraw: bool,
        receive_notifications: bool,
    ) -> ApiKeyConfigPermissionsInner {
        ApiKeyConfigPermissionsInner {
            account_number,
            may_view,
            may_trade,
            may_withdraw,
            receive_notifications,
        }
    }
}
