/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceSweep {
    /// The account ID to or from which the balance was swept.
    #[serde(rename = "sweep_account_id")]
    pub sweep_account_id: rust_decimal::Decimal,
}

impl BalanceSweep {
    pub fn new(sweep_account_id: rust_decimal::Decimal) -> BalanceSweep {
        BalanceSweep { sweep_account_id }
    }
}
