/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelBotParams {
    /// The `bot_id` returned when creating the bot, or calling `private/bots`.
    #[serde(rename = "bot_id")]
    pub bot_id: String,
}

impl CancelBotParams {
    pub fn new(bot_id: String) -> CancelBotParams {
        CancelBotParams { bot_id }
    }
}
