/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CancelBotResponse {
    CancelBotResult(models::CancelBotResult),
    RpcErrorResponse(models::RpcErrorResponse),
}

impl Default for CancelBotResponse {
    fn default() -> Self {
        Self::CancelBotResult(Default::default())
    }
}
