/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelMassQuoteParams {
    /// If set, only the mass quotes on this product will be cancelled.
    #[serde(rename = "product", skip_serializing_if = "Option::is_none")]
    pub product: Option<String>,
}

impl CancelMassQuoteParams {
    pub fn new() -> CancelMassQuoteParams {
        CancelMassQuoteParams { product: None }
    }
}
