/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CollarEnum {
    #[serde(rename = "ignore")]
    Ignore,
    #[serde(rename = "reject")]
    Reject,
    #[serde(rename = "clamp")]
    Clamp,
}

impl std::fmt::Display for CollarEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ignore => write!(f, "ignore"),
            Self::Reject => write!(f, "reject"),
            Self::Clamp => write!(f, "clamp"),
        }
    }
}

impl Default for CollarEnum {
    fn default() -> CollarEnum {
        Self::Ignore
    }
}
