/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConditionalOrder {
    /// Unique ID, use to identify in cancel
    #[serde(rename = "order_id")]
    pub order_id: String,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "direction")]
    pub direction: Direction,
    /// Size of the order when activated
    #[serde(rename = "amount")]
    pub amount: f64,
    /// The trigger type that `stop_price` and `bracket_price` will refer to.
    #[serde(rename = "target")]
    pub target: Target,
    /// Trigger price at which the order will be activated
    #[serde(rename = "stop_price")]
    pub stop_price: f64,
    /// For stop limit order, the price at which the order will be placed
    #[serde(rename = "limit_price", skip_serializing_if = "Option::is_none")]
    pub limit_price: Option<f64>,
    /// For bracket order, the price at which profit will be taken (upper activation price)
    #[serde(rename = "bracket_price", skip_serializing_if = "Option::is_none")]
    pub bracket_price: Option<f64>,
    /// For trailing stop loss, the callback rate as a ratio (e.g. 0.05 for 5%)
    #[serde(
        rename = "trailing_stop_callback_rate",
        skip_serializing_if = "Option::is_none"
    )]
    pub trailing_stop_callback_rate: Option<f64>,
    /// Optional user label
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "create_time")]
    pub create_time: f64,
    /// Time of last update (conversion or change of trailing stop price)
    #[serde(rename = "update_time")]
    pub update_time: f64,
    /// Time of trigger
    #[serde(rename = "convert_time", skip_serializing_if = "Option::is_none")]
    pub convert_time: Option<f64>,
    /// System order ID of the created order.
    #[serde(rename = "converted_order_id", skip_serializing_if = "Option::is_none")]
    pub converted_order_id: Option<String>,
    /// If conversion failed, the reason
    #[serde(rename = "reject_reason", skip_serializing_if = "Option::is_none")]
    pub reject_reason: Option<String>,
    #[serde(rename = "reduce_only")]
    pub reduce_only: bool,
}

impl ConditionalOrder {
    pub fn new(
        order_id: String,
        instrument_name: String,
        direction: Direction,
        amount: f64,
        target: Target,
        stop_price: f64,
        status: Status,
        create_time: f64,
        update_time: f64,
        reduce_only: bool,
    ) -> ConditionalOrder {
        ConditionalOrder {
            order_id,
            instrument_name,
            direction,
            amount,
            target,
            stop_price,
            limit_price: None,
            bracket_price: None,
            trailing_stop_callback_rate: None,
            label: None,
            status,
            create_time,
            update_time,
            convert_time: None,
            converted_order_id: None,
            reject_reason: None,
            reduce_only,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Buy
    }
}
/// The trigger type that `stop_price` and `bracket_price` will refer to.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Target {
    #[serde(rename = "last")]
    Last,
    #[serde(rename = "mark")]
    Mark,
    #[serde(rename = "index")]
    Index,
}

impl Default for Target {
    fn default() -> Target {
        Self::Last
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "converted")]
    Converted,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "cancel requested")]
    CancelRequested,
    #[serde(rename = "cancelled")]
    Cancelled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Created
    }
}
