/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DHedge {
    /// Individually identifies this bot instance. You can use it to cancel this specific one.
    #[serde(rename = "bot_id")]
    pub bot_id: String,
    /// Equal to \"dhedge\".
    #[serde(rename = "strategy")]
    pub strategy: String,
    #[serde(rename = "status")]
    pub status: Status,
    /// Name of the instrument the bot will trade.
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    /// Name of an instrument. If specified, the bot will only hedge the position in this instrument, not the entire underlying.
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<String>,
    /// The delta that the bot is targeting.
    #[serde(rename = "target_delta")]
    pub target_delta: rust_decimal::Decimal,
    /// Tolerance threshold.
    #[serde(rename = "threshold")]
    pub threshold: rust_decimal::Decimal,
    /// Maximum deviation allowed from target deltas at any time.
    #[serde(rename = "tolerance", skip_serializing_if = "Option::is_none")]
    pub tolerance: Option<rust_decimal::Decimal>,
    /// Number of seconds to let the deltas stay outside of `[target-threshold, target+threshold]`, before hedging them.
    #[serde(rename = "period")]
    pub period: rust_decimal::Decimal,
    /// Maximum slippage per trade, expressed as % of the traded instruments mark price.
    #[serde(rename = "max_slippage", skip_serializing_if = "Option::is_none")]
    pub max_slippage: Option<rust_decimal::Decimal>,
    /// Timestamp when the bot should stop executing. If not specified, the bot will run until it's manually stopped. When `end_time` is reached, the bot will leave all positions intact, it will not open/close any of them.
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<rust_decimal::Decimal>,
    /// Timestamp indicating when the bot was created.
    #[serde(rename = "start_time")]
    pub start_time: rust_decimal::Decimal,
    /// Timestamp indicating when the bot stopped working due to specified `stop_reason`.
    #[serde(rename = "stop_time", skip_serializing_if = "Option::is_none")]
    pub stop_time: Option<rust_decimal::Decimal>,
    /// The reason why the bot stopped executing.
    #[serde(rename = "stop_reason", skip_serializing_if = "Option::is_none")]
    pub stop_reason: Option<StopReason>,
    /// A label that the bot will add to all orders for easy identification.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Realized P&L made by this bot since the start.
    #[serde(rename = "realized_pnl")]
    pub realized_pnl: rust_decimal::Decimal,
    /// Trade fees by this bot.
    #[serde(rename = "fee")]
    pub fee: rust_decimal::Decimal,
    /// Average entry price of the position (if any).
    #[serde(rename = "average_price", skip_serializing_if = "Option::is_none")]
    pub average_price: Option<rust_decimal::Decimal>,
    /// Position size (if any).
    #[serde(rename = "position_size", skip_serializing_if = "Option::is_none")]
    pub position_size: Option<rust_decimal::Decimal>,
    /// Mark price of the bot instrument at the moment the bot was stopped.
    #[serde(rename = "mark_price_at_stop", skip_serializing_if = "Option::is_none")]
    pub mark_price_at_stop: Option<rust_decimal::Decimal>,
}

impl DHedge {
    pub fn new(
        bot_id: String,
        strategy: String,
        status: Status,
        instrument_name: String,
        target_delta: rust_decimal::Decimal,
        threshold: rust_decimal::Decimal,
        period: rust_decimal::Decimal,
        start_time: rust_decimal::Decimal,
        realized_pnl: rust_decimal::Decimal,
        fee: rust_decimal::Decimal,
    ) -> DHedge {
        DHedge {
            bot_id,
            strategy,
            status,
            instrument_name,
            position: None,
            target_delta,
            threshold,
            tolerance: None,
            period,
            max_slippage: None,
            end_time: None,
            start_time,
            stop_time: None,
            stop_reason: None,
            label: None,
            realized_pnl,
            fee,
            average_price: None,
            position_size: None,
            mark_price_at_stop: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "stopped")]
    Stopped,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}
/// The reason why the bot stopped executing.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StopReason {
    #[serde(rename = "client_cancel")]
    ClientCancel,
    #[serde(rename = "client_bulk_cancel")]
    ClientBulkCancel,
    #[serde(rename = "end_time")]
    EndTime,
    #[serde(rename = "instrument_deactivated")]
    InstrumentDeactivated,
    #[serde(rename = "margin_breach")]
    MarginBreach,
    #[serde(rename = "admin_cancel")]
    AdminCancel,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "strategy")]
    Strategy,
    #[serde(rename = "self_trade_prevention")]
    SelfTradePrevention,
}

impl Default for StopReason {
    fn default() -> StopReason {
        Self::ClientCancel
    }
}
