/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DHedge1 {
    /// Equal to \"dhedge\".
    #[serde(rename = "strategy")]
    pub strategy: String,
    /// Name of the instrument the bot will trade.
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    /// Name of an instrument. If specified, the bot will only hedge the position in this instrument, not the entire underlying.
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<String>,
    /// The delta that the bot is targeting.
    #[serde(rename = "target_delta")]
    pub target_delta: f64,
    /// Tolerance threshold.
    #[serde(rename = "threshold")]
    pub threshold: f64,
    /// Number of seconds to let the deltas stay outside of `[target-threshold, target+threshold]`, before hedging them.
    #[serde(rename = "period")]
    pub period: f64,
    /// Maximum slippage per trade, expressed as % of the traded instruments mark price.
    #[serde(rename = "max_slippage", skip_serializing_if = "Option::is_none")]
    pub max_slippage: Option<f64>,
    /// Timestamp when the bot should stop executing. If not specified, the bot will run until it's manually stopped. When `end_time` is reached, the bot will leave all positions intact, it will not open/close any of them.
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<f64>,
    /// A label that the bot will add to all orders for easy identification.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl DHedge1 {
    pub fn new(
        strategy: String,
        instrument_name: String,
        target_delta: f64,
        threshold: f64,
        period: f64,
    ) -> DHedge1 {
        DHedge1 {
            strategy,
            instrument_name,
            position: None,
            target_delta,
            threshold,
            period,
            max_slippage: None,
            end_time: None,
            label: None,
        }
    }
}
