/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DailyMark {
    /// Time of settlement (Unix timestamp).
    #[serde(rename = "time")]
    pub time: f64,
    /// Instrument name.
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    /// Position in the instrument.
    #[serde(rename = "position")]
    pub position: f64,
    /// Mark price used for settlement.
    #[serde(rename = "mark_price")]
    pub mark_price: f64,
    /// Realized profit or loss for this position.
    #[serde(rename = "realized_position_pnl")]
    pub realized_position_pnl: f64,
    /// Realized perpetual funding. Only present for perpetuals.
    #[serde(
        rename = "realized_funding_pnl",
        skip_serializing_if = "Option::is_none"
    )]
    pub realized_funding_pnl: Option<f64>,
}

impl DailyMark {
    pub fn new(
        time: f64,
        instrument_name: String,
        position: f64,
        mark_price: f64,
        realized_position_pnl: f64,
    ) -> DailyMark {
        DailyMark {
            time,
            instrument_name,
            position,
            mark_price,
            realized_position_pnl,
            realized_funding_pnl: None,
        }
    }
}
