/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Deposit {
    /// Deposited currency symbol.
    #[serde(rename = "currency")]
    pub currency: String,
    /// Amount of currency deposited.
    #[serde(rename = "amount")]
    pub amount: f64,
    /// Blockchain used or this transaction.
    #[serde(rename = "blockchain")]
    pub blockchain: String,
    /// Transaction hash on the used blockchain.
    #[serde(rename = "transaction_hash")]
    pub transaction_hash: String,
    /// Time when this transaction was created (Unix timestamp).
    #[serde(rename = "transaction_timestamp")]
    pub transaction_timestamp: f64,
    /// Deposit transaction status.
    #[serde(rename = "status")]
    pub status: Status,
    /// Number of confirmations. Optional, omitted when none.
    #[serde(rename = "confirmations", skip_serializing_if = "Option::is_none")]
    pub confirmations: Option<f64>,
}

impl Deposit {
    pub fn new(
        currency: String,
        amount: f64,
        blockchain: String,
        transaction_hash: String,
        transaction_timestamp: f64,
        status: Status,
    ) -> Deposit {
        Deposit {
            currency,
            amount,
            blockchain,
            transaction_hash,
            transaction_timestamp,
            status,
            confirmations: None,
        }
    }
}
/// Deposit transaction status.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "unconfirmed")]
    Unconfirmed,
    #[serde(rename = "confirmed")]
    Confirmed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unconfirmed
    }
}
