/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DoubleSidedQuoteB {
    /// an array of bid quotes
    Array(Vec<Vec<serde_json::Value>>),
    SingleLevelQuote(Box<models::SingleLevelQuote>),
}

impl Default for DoubleSidedQuoteB {
    fn default() -> Self {
        Self::Array(Default::default())
    }
}
