/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DoubleSidedQuote {
    /// instrument name
    #[serde(rename = "i")]
    pub i: String,
    #[serde(rename = "b", skip_serializing_if = "Option::is_none")]
    pub b: Option<Box<models::DoubleSidedQuoteB>>,
    #[serde(rename = "a", skip_serializing_if = "Option::is_none")]
    pub a: Option<Box<models::DoubleSidedQuoteA>>,
}

impl DoubleSidedQuote {
    pub fn new(i: String) -> DoubleSidedQuote {
        DoubleSidedQuote {
            i,
            b: None,
            a: None,
        }
    }
}
