/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DoubleSidedQuoteA {
    /// an array of ask quotes
    Array(Vec<Vec<serde_json::Value>>),
    SingleLevelQuote1(models::SingleLevelQuote1),
}

impl Default for DoubleSidedQuoteA {
    fn default() -> Self {
        Self::Array(Default::default())
    }
}
