/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DoubleSidedQuoteA {
    /// an array of ask quotes
    Array(Vec<Vec<serde_json::Value>>),
    SingleLevelQuote1(Box<models::SingleLevelQuote1>),
}

impl Default for DoubleSidedQuoteA {
    fn default() -> Self {
        Self::Array(Default::default())
    }
}
