/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

/// DoubleSidedQuoteB : Bid quote(s)
/// Bid quote(s)
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DoubleSidedQuoteB {
    SingleSidedMultiLevelQuote(Vec<[Decimal; 2]>), // [price, amount],
    SingleSidedSingleLevelQuote(models::SingleSidedSingleLevelQuote),
}

impl Default for DoubleSidedQuoteB {
    fn default() -> Self {
        Self::SingleSidedMultiLevelQuote(Default::default())
    }
}
