/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DoubleSidedQuote {
    /// instrument name
    #[serde(rename = "i")]
    pub i: String,
    #[serde(rename = "b", skip_serializing_if = "Option::is_none")]
    pub b: Option<models::DoubleSidedQuoteB>,
    #[serde(rename = "a", skip_serializing_if = "Option::is_none")]
    pub a: Option<models::DoubleSidedQuoteA>,
}

impl DoubleSidedQuote {
    pub fn new(i: String) -> DoubleSidedQuote {
        DoubleSidedQuote {
            i,
            b: None,
            a: None,
        }
    }
}
