/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Grid {
    /// Individually identifies this bot instance. You can use it to cancel this specific one.
    #[serde(rename = "bot_id")]
    pub bot_id: String,
    /// One of [\"active\", \"stopped\"].
    #[serde(rename = "status")]
    pub status: String,
    /// The reason why the bot stopped executing. Possible values are [\"client_cancel\", \"client_bulk_cancel\", \"end_time\", \"instrument_deactivated\", \"margin_breach\", \"admin_cancel\", \"conflict\", \"strategy\"].
    #[serde(rename = "stop_reason", skip_serializing_if = "Option::is_none")]
    pub stop_reason: Option<String>,
    /// Equal to \"grid\".
    #[serde(rename = "strategy")]
    pub strategy: String,
    /// Name of the instrument the bot instance is trading.
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    /// The default price levels the bot will be quoting at. See [the bot strategies section](#tag/bot_strategies) for more explanation.
    #[serde(rename = "grid")]
    pub grid: Vec<f64>,
    /// As long as the account's portfolio position in the instrument that the bot is trading is equal to base_position, the bot will insert step_size asks on the grid above target_mean_price (one per level), and step_size bids below target_mean_price.
    #[serde(rename = "target_mean_price")]
    pub target_mean_price: f64,
    /// The default size to quote on one level. See [the bot strategies section](#tag/bot_strategies) for more explanation.
    #[serde(rename = "step_size")]
    pub step_size: f64,
    /// Will be used as a reference to compare the subaccount's portfolio position in the instrument that this bot is trading to. See [the bot strategies section](#tag/bot_strategies) for more explanation.
    #[serde(rename = "base_position")]
    pub base_position: f64,
    /// If the mark price of the instrument this bot is trading goes above `upside_exit_price`, the bot cancels the maker orders, aggressively trades into `base_position`, and then stops executing.
    #[serde(rename = "upside_exit_price", skip_serializing_if = "Option::is_none")]
    pub upside_exit_price: Option<f64>,
    /// If the mark price of the instrument this bot is trading goes below `downside_exit_price`, the bot cancels the maker orders, aggressively trades into `base_position`, and then stops executing.
    #[serde(
        rename = "downside_exit_price",
        skip_serializing_if = "Option::is_none"
    )]
    pub downside_exit_price: Option<f64>,
    /// Maximum slippage per trade when exiting any position, expressed as % of the traded instruments mark price.
    #[serde(rename = "max_slippage", skip_serializing_if = "Option::is_none")]
    pub max_slippage: Option<f64>,
    /// Timestamp when the bot stops executing, cancelling its orders and leaving all positions of the subaccount intact.
    #[serde(rename = "end_time")]
    pub end_time: f64,
    /// A label that the bot will add to all orders for easy identification.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Realized P&L made by this bot since the start.
    #[serde(rename = "realized_pnl")]
    pub realized_pnl: f64,
    /// Trade fees by this bot.
    #[serde(rename = "fee")]
    pub fee: f64,
    /// Average entry price of the position (if any).
    #[serde(rename = "average_price", skip_serializing_if = "Option::is_none")]
    pub average_price: Option<f64>,
    /// Position size (if any).
    #[serde(rename = "position_size", skip_serializing_if = "Option::is_none")]
    pub position_size: Option<f64>,
    /// Mark price of the bot instrument at the moment the bot was stopped.
    #[serde(rename = "mark_price_at_stop", skip_serializing_if = "Option::is_none")]
    pub mark_price_at_stop: Option<f64>,
}

impl Grid {
    pub fn new(
        bot_id: String,
        status: String,
        strategy: String,
        instrument_name: String,
        grid: Vec<f64>,
        target_mean_price: f64,
        step_size: f64,
        base_position: f64,
        end_time: f64,
        realized_pnl: f64,
        fee: f64,
    ) -> Grid {
        Grid {
            bot_id,
            status,
            stop_reason: None,
            strategy,
            instrument_name,
            grid,
            target_mean_price,
            step_size,
            base_position,
            upside_exit_price: None,
            downside_exit_price: None,
            max_slippage: None,
            end_time,
            label: None,
            realized_pnl,
            fee,
            average_price: None,
            position_size: None,
            mark_price_at_stop: None,
        }
    }
}
