/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Grid1 {
    /// Equal to \"grid\".
    #[serde(rename = "strategy")]
    pub strategy: String,
    /// Name of the instrument to run the Grid bot on.
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    /// The default price levels the bot will be quoting at. Must have minimum 2, maximum 8 levels. Distance between quote levels must minimum 5, maximum 100 ticks. See [the bot strategies section](#tag/bot_strategies) for more explanation.
    #[serde(rename = "grid")]
    pub grid: Vec<f64>,
    /// The default size to quote on one level. Must not be greater than 100 volume ticks. See [the bot strategies section](#tag/bot_strategies) for more explanation.
    #[serde(rename = "step_size")]
    pub step_size: f64,
    /// Will be used as a reference to compare the subaccount's portfolio position in the instrument that this bot is trading to. Defaults to the portfolio position of the subaccount in `instrument_name` at the time of sending the request. See [the bot strategies section](#tag/bot_strategies) for more explanation.
    #[serde(rename = "base_position", skip_serializing_if = "Option::is_none")]
    pub base_position: Option<f64>,
    /// As long as the account's portfolio position in the instrument that the bot is trading is equal to base_position, the bot will insert step_size asks on the grid above target_mean_price (one per level), and step_size bids below target_mean_price.
    #[serde(rename = "target_mean_price", skip_serializing_if = "Option::is_none")]
    pub target_mean_price: Option<f64>,
    /// If the mark price of the instrument this bot is trading goes above `upside_exit_price`, the bot cancels the maker orders, aggressively trades into `base_position`, and then stops executing. Must not be more than 200 ticks away from highest quote.
    #[serde(rename = "upside_exit_price", skip_serializing_if = "Option::is_none")]
    pub upside_exit_price: Option<f64>,
    /// If the mark price of the instrument this bot is trading goes below `downside_exit_price`, the bot cancels the maker orders, aggressively trades into `base_position`, and then stops executing. Must not be more than 200 ticks away from lowest quote.
    #[serde(
        rename = "downside_exit_price",
        skip_serializing_if = "Option::is_none"
    )]
    pub downside_exit_price: Option<f64>,
    /// Maximum slippage per trade when exiting any position, expressed as % of the traded instruments mark price.
    #[serde(rename = "max_slippage", skip_serializing_if = "Option::is_none")]
    pub max_slippage: Option<f64>,
    /// Timestamp when the bot should stop executing. Must not be further away than a week. When `end_time` is reached, the bot will leave all positions intact, it will not open/close any of them.
    #[serde(rename = "end_time")]
    pub end_time: f64,
    /// A label that the bot will add to all orders for easy identification.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl Grid1 {
    pub fn new(
        strategy: String,
        instrument_name: String,
        grid: Vec<f64>,
        step_size: f64,
        end_time: f64,
    ) -> Grid1 {
        Grid1 {
            strategy,
            instrument_name,
            grid,
            step_size,
            base_position: None,
            target_mean_price: None,
            upside_exit_price: None,
            downside_exit_price: None,
            max_slippage: None,
            end_time,
            label: None,
        }
    }
}
