/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsertRequestLegsInner {
    /// Name of the instrument to trade on this leg.
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    /// Quantity of this leg in a unit of the combination. Must be integer. Must not be zero. Use a negative number for short legs.  Result of multiplication of `quantity` and order `amount` must be aligned to tick size for every leg.
    #[serde(rename = "quantity")]
    pub quantity: f64,
}

impl InsertRequestLegsInner {
    pub fn new(instrument_name: String, quantity: f64) -> InsertRequestLegsInner {
        InsertRequestLegsInner {
            instrument_name,
            quantity,
        }
    }
}
