/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstrumentParams {
    /// Name of the instrument to query.
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
}

impl InstrumentParams {
    pub fn new(instrument_name: String) -> InstrumentParams {
        InstrumentParams { instrument_name }
    }
}
