/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InstrumentTypeEnum {
    #[serde(rename = "futures")]
    Futures,
    #[serde(rename = "options")]
    Options,
    #[serde(rename = "future_rolls")]
    FutureRolls,
}

impl std::fmt::Display for InstrumentTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Futures => write!(f, "futures"),
            Self::Options => write!(f, "options"),
            Self::FutureRolls => write!(f, "future_rolls"),
        }
    }
}

impl Default for InstrumentTypeEnum {
    fn default() -> InstrumentTypeEnum {
        Self::Futures
    }
}
