/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstrumentsPayloadInnerOneOf {
    #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
    pub added: Option<models::Instrument>,
}

impl InstrumentsPayloadInnerOneOf {
    pub fn new() -> InstrumentsPayloadInnerOneOf {
        InstrumentsPayloadInnerOneOf { added: None }
    }
}
