/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InstrumentsPayloadInner {
    InstrumentsPayloadInnerOneOf(models::InstrumentsPayloadInnerOneOf),
    InstrumentsPayloadInnerOneOf1(models::InstrumentsPayloadInnerOneOf1),
}

impl Default for InstrumentsPayloadInner {
    fn default() -> Self {
        Self::InstrumentsPayloadInnerOneOf(Default::default())
    }
}
