/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstrumentsPayloadInnerOneOf1 {
    #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
    pub removed: Option<models::Instrument>,
}

impl InstrumentsPayloadInnerOneOf1 {
    pub fn new() -> InstrumentsPayloadInnerOneOf1 {
        InstrumentsPayloadInnerOneOf1 { removed: None }
    }
}
