/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InternalTransferParams {
    /// Destination account number.
    #[serde(rename = "destination_account_number")]
    pub destination_account_number: String,
    #[serde(rename = "assets", skip_serializing_if = "Option::is_none")]
    pub assets: Option<Vec<models::VerifyInternalTransferParamsAssetsInner>>,
    #[serde(rename = "positions", skip_serializing_if = "Option::is_none")]
    pub positions: Option<Vec<models::VerifyInternalTransferParamsPositionsInner>>,
    /// Optional label attached to the transfer.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl InternalTransferParams {
    pub fn new(destination_account_number: String) -> InternalTransferParams {
        InternalTransferParams {
            destination_account_number,
            assets: None,
            positions: None,
            label: None,
        }
    }
}
