/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginParams {
    /// As described in 'Authentication'
    #[serde(rename = "token")]
    pub token: String,
    /// Number of an account to select for use in this session. Optional, if not specified, default account for the API key is selected.
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<String>,
}

impl LoginParams {
    pub fn new(token: String) -> LoginParams {
        LoginParams {
            token,
            account: None,
        }
    }
}
