/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginBreakdownWithOrderWithBuy {
    /// Total required margin for account with the order inserted as buy.
    #[serde(rename = "required_margin", skip_serializing_if = "Option::is_none")]
    pub required_margin: Option<rust_decimal::Decimal>,
    #[serde(rename = "underlying", skip_serializing_if = "Option::is_none")]
    pub underlying: Option<models::MarginBreakdownWithOrderCurrentUnderlying>,
}

impl MarginBreakdownWithOrderWithBuy {
    pub fn new() -> MarginBreakdownWithOrderWithBuy {
        MarginBreakdownWithOrderWithBuy {
            required_margin: None,
            underlying: None,
        }
    }
}
