/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginBreakdownWithOrderCurrent {
    /// Total required margin for account.
    #[serde(rename = "required_margin", skip_serializing_if = "Option::is_none")]
    pub required_margin: Option<f64>,
    #[serde(rename = "underlying", skip_serializing_if = "Option::is_none")]
    pub underlying: Option<Box<models::MarginBreakdownWithOrderCurrentUnderlying>>,
}

impl MarginBreakdownWithOrderCurrent {
    pub fn new() -> MarginBreakdownWithOrderCurrent {
        MarginBreakdownWithOrderCurrent {
            required_margin: None,
            underlying: None,
        }
    }
}
