/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MassQuoteResponse {
    MassQuoteResult(models::MassQuoteResult),
    RpcErrorResponse(models::RpcErrorResponse),
}

impl Default for MassQuoteResponse {
    fn default() -> Self {
        Self::MassQuoteResult(Default::default())
    }
}
