/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MassQuoteSingleLevelQuote {
    /// an array of quotes
    Array(Vec<[Decimal; 2]>), // [price, amount]
    SingleLevelQuote(models::SingleLevelQuote),
}

impl Default for MassQuoteSingleLevelQuote {
    fn default() -> Self {
        Self::Array(Default::default())
    }
}
