/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotificationPreferencesApiKeyValue : Map of notification preferences per category.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationPreferencesApiKeyValue {
    /// Notification is placed in user/api key inbox.
    #[serde(rename = "inbox", skip_serializing_if = "Option::is_none")]
    pub inbox: Option<bool>,
}

impl NotificationPreferencesApiKeyValue {
    /// Map of notification preferences per category.
    pub fn new() -> NotificationPreferencesApiKeyValue {
        NotificationPreferencesApiKeyValue { inbox: None }
    }
}
