/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotificationPreferencesValue : Map of notification preferences per category.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationPreferencesValue {
    /// E-mail message is sent for this notification.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<bool>,
    /// Notification is placed in user/api key inbox.
    #[serde(rename = "inbox", skip_serializing_if = "Option::is_none")]
    pub inbox: Option<bool>,
    /// For user inbox notifications, determines if a popup is shown in the front end.
    #[serde(rename = "popup", skip_serializing_if = "Option::is_none")]
    pub popup: Option<bool>,
    /// SMS message is sent for this notification.
    #[serde(rename = "sms", skip_serializing_if = "Option::is_none")]
    pub sms: Option<bool>,
}

impl NotificationPreferencesValue {
    /// Map of notification preferences per category.
    pub fn new() -> NotificationPreferencesValue {
        NotificationPreferencesValue {
            email: None,
            inbox: None,
            popup: None,
            sms: None,
        }
    }
}
