/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ocq1 {
    /// Individually identifies this bot instance. You can use it to cancel this specific one.
    #[serde(rename = "bot_id")]
    pub bot_id: String,
    #[serde(rename = "status")]
    pub status: Status,
    /// The reason why the bot stopped executing. Possible values are [\"client_cancel\", \"client_bulk_cancel\", \"end_time\", \"instrument_deactivated\", \"margin_breach\", \"admin_cancel\", \"conflict\", \"strategy\"].
    #[serde(rename = "stop_reason", skip_serializing_if = "Option::is_none")]
    pub stop_reason: Option<String>,
    /// equal to \"ocq\"
    #[serde(rename = "strategy")]
    pub strategy: String,
    /// Name of the instrument.
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "signal")]
    pub signal: Signal,
    /// The offset of the price of the bid quote from the signal price. See [the bot strategies section](#tag/bot_strategies) for more explanation.
    #[serde(rename = "bid_offset")]
    pub bid_offset: f64,
    /// The offset of the price of the ask quote from the signal price. See [the bot strategies section](#tag/bot_strategies) for more explanation.
    #[serde(rename = "ask_offset")]
    pub ask_offset: f64,
    /// The default size of both the bid and ask quote, See [the bot strategies section](#tag/bot_strategies) for more explanation.
    #[serde(rename = "quote_size")]
    pub quote_size: f64,
    /// The minimum portfolio position to maintain in the subaccount. See [the bot strategies section](#tag/bot_strategies) for more explanation.
    #[serde(rename = "min_position")]
    pub min_position: f64,
    /// The maximum portfolio position to maintain in the subaccount. See [the bot strategies section](#tag/bot_strategies) for more explanation.
    #[serde(rename = "max_position")]
    pub max_position: f64,
    /// Timestamp when the bot stops executing, cancelling its orders and leaving all positions of the subaccount intact.
    #[serde(rename = "end_time")]
    pub end_time: f64,
    /// A label that the bot will add to all orders for easy identification.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl Ocq1 {
    pub fn new(
        bot_id: String,
        status: Status,
        strategy: String,
        instrument_name: String,
        signal: Signal,
        bid_offset: f64,
        ask_offset: f64,
        quote_size: f64,
        min_position: f64,
        max_position: f64,
        end_time: f64,
    ) -> Ocq1 {
        Ocq1 {
            bot_id,
            status,
            stop_reason: None,
            strategy,
            instrument_name,
            signal,
            bid_offset,
            ask_offset,
            quote_size,
            min_position,
            max_position,
            end_time,
            label: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "stopped")]
    Stopped,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Signal {
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "mark")]
    Mark,
}

impl Default for Signal {
    fn default() -> Signal {
        Self::Index
    }
}
