/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderFill {
    /// Trade ID.
    #[serde(rename = "trade_id")]
    pub trade_id: String,
    /// Fill price.
    #[serde(rename = "price")]
    pub price: f64,
    /// Filled amount
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<f64>,
    /// Maker (trade on book order) or taker (trade on new order), if applicable.
    #[serde(rename = "maker_taker")]
    pub maker_taker: MakerTaker,
    /// Index of a leg on which the trade happened for combination orders. Zero for single-leg orders.  For combination orders the direction of the trade is defined by the direction of the order and the sign of the leg quantity.
    #[serde(rename = "leg_index")]
    pub leg_index: f64,
}

impl OrderFill {
    pub fn new(
        trade_id: String,
        price: f64,
        amount: f64,
        maker_taker: MakerTaker,
        leg_index: f64,
    ) -> OrderFill {
        OrderFill {
            trade_id,
            price,
            amount,
            time: None,
            maker_taker,
            leg_index,
        }
    }
}
/// Maker (trade on book order) or taker (trade on new order), if applicable.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MakerTaker {
    #[serde(rename = "maker")]
    Maker,
    #[serde(rename = "taker")]
    Taker,
}

impl Default for MakerTaker {
    fn default() -> MakerTaker {
        Self::Maker
    }
}
