/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PortfolioMarginBreakdown : Required margin breakdown for accounts that use portfolio margin.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortfolioMarginBreakdown {
    #[serde(rename = "portfolio", skip_serializing_if = "Option::is_none")]
    pub portfolio: Option<Box<models::PortfolioMarginBreakdownPortfolio>>,
}

impl PortfolioMarginBreakdown {
    /// Required margin breakdown for accounts that use portfolio margin.
    pub fn new() -> PortfolioMarginBreakdown {
        PortfolioMarginBreakdown { portfolio: None }
    }
}
