/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortfolioMarginBreakdownPortfolio {
    /// Total required margin for account.
    #[serde(rename = "required_margin", skip_serializing_if = "Option::is_none")]
    pub required_margin: Option<f64>,
    #[serde(rename = "underlyings", skip_serializing_if = "Option::is_none")]
    pub underlyings: Option<Vec<models::PortfolioMarginBreakdownPortfolioUnderlyingsInner>>,
}

impl PortfolioMarginBreakdownPortfolio {
    pub fn new() -> PortfolioMarginBreakdownPortfolio {
        PortfolioMarginBreakdownPortfolio {
            required_margin: None,
            underlyings: None,
        }
    }
}
