/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateVerifyInternalTransferRequest {
    /// Destination account number.
    #[serde(rename = "destination_account_number")]
    pub destination_account_number: String,
    #[serde(rename = "assets", skip_serializing_if = "Option::is_none")]
    pub assets: Option<Vec<models::PrivateVerifyInternalTransferRequestAssetsInner>>,
    #[serde(rename = "positions", skip_serializing_if = "Option::is_none")]
    pub positions: Option<Vec<models::PrivateVerifyInternalTransferRequestPositionsInner>>,
}

impl PrivateVerifyInternalTransferRequest {
    pub fn new(destination_account_number: String) -> PrivateVerifyInternalTransferRequest {
        PrivateVerifyInternalTransferRequest {
            destination_account_number,
            assets: None,
            positions: None,
        }
    }
}
