/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateTransactionHistoryInlinePropertiesTransactionsItems {
    #[serde(rename = "time")]
    pub time: f64,
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "instrument_name", skip_serializing_if = "Option::is_none")]
    pub instrument_name: Option<String>,
    #[serde(rename = "transaction_type", skip_serializing_if = "Option::is_none")]
    pub transaction_type: Option<TransactionType>,
    #[serde(rename = "balance_after", skip_serializing_if = "Option::is_none")]
    pub balance_after: Option<f64>,
}

impl PrivateTransactionHistoryInlinePropertiesTransactionsItems {
    pub fn new(
        time: f64,
        asset: String,
        amount: f64,
    ) -> PrivateTransactionHistoryInlinePropertiesTransactionsItems {
        PrivateTransactionHistoryInlinePropertiesTransactionsItems {
            time,
            asset,
            amount,
            instrument_name: None,
            transaction_type: None,
            balance_after: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionType {
    #[serde(rename = "deposit")]
    Deposit,
    #[serde(rename = "withdrawal")]
    Withdrawal,
    #[serde(rename = "withdrawal fee")]
    WithdrawalFee,
    #[serde(rename = "session settlement")]
    SessionSettlement,
    #[serde(rename = "perpetual funding")]
    PerpetualFunding,
    #[serde(rename = "internal transfer")]
    InternalTransfer,
    #[serde(rename = "asset swap")]
    AssetSwap,
    #[serde(rename = "referral program payment")]
    ReferralProgramPayment,
    #[serde(rename = "market velocity program payment")]
    MarketVelocityProgramPayment,
    #[serde(rename = "market quality program payment")]
    MarketQualityProgramPayment,
    #[serde(rename = "daily interest")]
    DailyInterest,
}

impl Default for TransactionType {
    fn default() -> TransactionType {
        Self::Deposit
    }
}
