/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateRequiredMarginForOrderLegsParameterInner {
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    /// Quantity for this leg. May be negative.
    #[serde(rename = "quantity")]
    pub quantity: f64,
}

impl PrivateRequiredMarginForOrderLegsParameterInner {
    pub fn new(
        instrument_name: String,
        quantity: f64,
    ) -> PrivateRequiredMarginForOrderLegsParameterInner {
        PrivateRequiredMarginForOrderLegsParameterInner {
            instrument_name,
            quantity,
        }
    }
}
