/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrivateCreateRfq {
    Rfq(Box<models::Rfq>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for PrivateCreateRfq {
    fn default() -> Self {
        Self::Rfq(Default::default())
    }
}
/// Detailed reason for creation. Visible only to the requester.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InsertReason {
    #[serde(rename = "client_request")]
    ClientRequest,
    #[serde(rename = "liquidation")]
    Liquidation,
}

impl Default for InsertReason {
    fn default() -> InsertReason {
        Self::ClientRequest
    }
}
/// Reason why this RFQ was removed. Visible only to the requester.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeleteReason {
    #[serde(rename = "client_cancel")]
    ClientCancel,
    #[serde(rename = "filled")]
    Filled,
}

impl Default for DeleteReason {
    fn default() -> DeleteReason {
        Self::ClientCancel
    }
}
/// This field is set only on the `account.rfqs` subscription.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "Created")]
    Created,
    #[serde(rename = "Cancelled")]
    Cancelled,
    #[serde(rename = "Traded")]
    Traded,
    #[serde(rename = "Existing")]
    Existing,
}

impl Default for Event {
    fn default() -> Event {
        Self::Created
    }
}
