/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrivateTradeHistory {
    PrivateTradeHistoryResult(Box<models::PrivateTradeHistoryResult>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for PrivateTradeHistory {
    fn default() -> Self {
        Self::PrivateTradeHistoryResult(Default::default())
    }
}
