/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateCryptoWithdrawalsInlineItems {
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "target_address")]
    pub target_address: String,
    #[serde(rename = "blockchain", skip_serializing_if = "Option::is_none")]
    pub blockchain: Option<String>,
    #[serde(rename = "transaction_hash", skip_serializing_if = "Option::is_none")]
    pub transaction_hash: Option<String>,
    #[serde(rename = "create_time")]
    pub create_time: f64,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "state")]
    pub state: State,
    #[serde(rename = "remark", skip_serializing_if = "Option::is_none")]
    pub remark: Option<String>,
    #[serde(rename = "fee", skip_serializing_if = "Option::is_none")]
    pub fee: Option<f64>,
    #[serde(rename = "fee_asset", skip_serializing_if = "Option::is_none")]
    pub fee_asset: Option<String>,
}

impl PrivateCryptoWithdrawalsInlineItems {
    pub fn new(
        currency: String,
        amount: f64,
        target_address: String,
        create_time: f64,
        state: State,
    ) -> PrivateCryptoWithdrawalsInlineItems {
        PrivateCryptoWithdrawalsInlineItems {
            currency,
            amount,
            target_address,
            blockchain: None,
            transaction_hash: None,
            create_time,
            label: None,
            state,
            remark: None,
            fee: None,
            fee_asset: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "awaiting_confirmation")]
    AwaitingConfirmation,
    #[serde(rename = "executing")]
    Executing,
    #[serde(rename = "executed")]
    Executed,
    #[serde(rename = "rejected")]
    Rejected,
}

impl Default for State {
    fn default() -> State {
        Self::Pending
    }
}
