/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrivateCreateConditionalOrder {
    PrivateCreateConditionalOrderResult(Box<models::ConditionalOrder>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for PrivateCreateConditionalOrder {
    fn default() -> Self {
        Self::PrivateCreateConditionalOrderResult(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Buy
    }
}
/// The trigger type that `stop_price` and `bracket_price` will refer to.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Target {
    #[serde(rename = "last")]
    Last,
    #[serde(rename = "mark")]
    Mark,
    #[serde(rename = "index")]
    Index,
}

impl Default for Target {
    fn default() -> Target {
        Self::Last
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "converted")]
    Converted,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "cancel requested")]
    CancelRequested,
    #[serde(rename = "cancelled")]
    Cancelled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Created
    }
}
