/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrivateAccountBreakdown {
    PrivateAccountBreakdownResult(Box<models::PrivateAccountBreakdownResult>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for PrivateAccountBreakdown {
    fn default() -> Self {
        Self::PrivateAccountBreakdownResult(Default::default())
    }
}
