/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateMarkInboxNotificationAsReadRequest {
    /// ID of the notification to mark.
    #[serde(rename = "notification_id")]
    pub notification_id: String,
    /// Set to `true` to mark as read, `false` to mark as not read.
    #[serde(rename = "read", skip_serializing_if = "Option::is_none")]
    pub read: Option<bool>,
}

impl PrivateMarkInboxNotificationAsReadRequest {
    pub fn new(notification_id: String) -> PrivateMarkInboxNotificationAsReadRequest {
        PrivateMarkInboxNotificationAsReadRequest {
            notification_id,
            read: None,
        }
    }
}
