/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateVerifyInternalTransferRequestPositionsInner {
    /// Instrument feedcode.
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    /// Amount to transfer. Use a negative value to transfer in reverse direction.
    #[serde(rename = "amount")]
    pub amount: f64,
}

impl PrivateVerifyInternalTransferRequestPositionsInner {
    pub fn new(
        instrument_name: String,
        amount: f64,
    ) -> PrivateVerifyInternalTransferRequestPositionsInner {
        PrivateVerifyInternalTransferRequestPositionsInner {
            instrument_name,
            amount,
        }
    }
}
