/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateCancelConditionalOrderRequest {
    #[serde(rename = "order_id")]
    pub order_id: String,
}

impl PrivateCancelConditionalOrderRequest {
    pub fn new(order_id: String) -> PrivateCancelConditionalOrderRequest {
        PrivateCancelConditionalOrderRequest { order_id }
    }
}
