/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateAccountBreakdownInlinePropertiesCashItems {
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "balance")]
    pub balance: f64,
    #[serde(rename = "collateral_factor")]
    pub collateral_factor: f64,
    #[serde(rename = "collateral_index_price")]
    pub collateral_index_price: f64,
    #[serde(rename = "applied_collateral")]
    pub applied_collateral: f64,
    #[serde(rename = "transactable")]
    pub transactable: bool,
}

impl PrivateAccountBreakdownInlinePropertiesCashItems {
    pub fn new(
        currency: String,
        balance: f64,
        collateral_factor: f64,
        collateral_index_price: f64,
        applied_collateral: f64,
        transactable: bool,
    ) -> PrivateAccountBreakdownInlinePropertiesCashItems {
        PrivateAccountBreakdownInlinePropertiesCashItems {
            currency,
            balance,
            collateral_factor,
            collateral_index_price,
            applied_collateral,
            transactable,
        }
    }
}
