/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrivateRequiredMarginForOrder {
    MarginBreakdownWithOrder(Box<models::MarginBreakdownWithOrder>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for PrivateRequiredMarginForOrder {
    fn default() -> Self {
        Self::MarginBreakdownWithOrder(Default::default())
    }
}
