/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateAccountBreakdownInlinePropertiesPortfolioItems {
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "position")]
    pub position: f64,
    #[serde(rename = "mark_price")]
    pub mark_price: f64,
    #[serde(rename = "start_price")]
    pub start_price: f64,
    #[serde(rename = "average_price")]
    pub average_price: f64,
    #[serde(rename = "unrealised_pnl_positional")]
    pub unrealised_pnl_positional: f64,
    #[serde(rename = "unrealised_pnl_perpetual")]
    pub unrealised_pnl_perpetual: f64,
    #[serde(rename = "unrealised_pnl")]
    pub unrealised_pnl: f64,
    #[serde(rename = "realised_position_pnl")]
    pub realised_position_pnl: f64,
    #[serde(rename = "open_buy_amount")]
    pub open_buy_amount: f64,
    #[serde(rename = "open_sell_amount")]
    pub open_sell_amount: f64,
    #[serde(rename = "session_realised_pnl")]
    pub session_realised_pnl: f64,
    #[serde(
        rename = "session_position_pnl",
        skip_serializing_if = "Option::is_none"
    )]
    pub session_position_pnl: Option<f64>,
    #[serde(
        rename = "session_perpetual_funding",
        skip_serializing_if = "Option::is_none"
    )]
    pub session_perpetual_funding: Option<f64>,
    #[serde(rename = "session_fees")]
    pub session_fees: f64,
}

impl PrivateAccountBreakdownInlinePropertiesPortfolioItems {
    pub fn new(
        instrument_name: String,
        position: f64,
        mark_price: f64,
        start_price: f64,
        average_price: f64,
        unrealised_pnl_positional: f64,
        unrealised_pnl_perpetual: f64,
        unrealised_pnl: f64,
        realised_position_pnl: f64,
        open_buy_amount: f64,
        open_sell_amount: f64,
        session_realised_pnl: f64,
        session_fees: f64,
    ) -> PrivateAccountBreakdownInlinePropertiesPortfolioItems {
        PrivateAccountBreakdownInlinePropertiesPortfolioItems {
            instrument_name,
            position,
            mark_price,
            start_price,
            average_price,
            unrealised_pnl_positional,
            unrealised_pnl_perpetual,
            unrealised_pnl,
            realised_position_pnl,
            open_buy_amount,
            open_sell_amount,
            session_realised_pnl,
            session_position_pnl: None,
            session_perpetual_funding: None,
            session_fees,
        }
    }
}
