/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateWithdrawRequest {
    /// Asset name.
    #[serde(rename = "asset_name")]
    pub asset_name: String,
    /// Amount to withdraw.
    #[serde(rename = "amount")]
    pub amount: f64,
    /// Target address.
    #[serde(rename = "target_address")]
    pub target_address: String,
    /// Optional label to attach to the withdrawal request.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl PrivateWithdrawRequest {
    pub fn new(asset_name: String, amount: f64, target_address: String) -> PrivateWithdrawRequest {
        PrivateWithdrawRequest {
            asset_name,
            amount,
            target_address,
            label: None,
        }
    }
}
