/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateCancelRfqRequest {
    /// The ID of the RFQ to be cancelled
    #[serde(rename = "rfq_id")]
    pub rfq_id: String,
}

impl PrivateCancelRfqRequest {
    pub fn new(rfq_id: String) -> PrivateCancelRfqRequest {
        PrivateCancelRfqRequest { rfq_id }
    }
}
