/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateCreateConditionalOrderRequest {
    #[serde(rename = "direction")]
    pub direction: Direction,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "amount")]
    pub amount: f64,
    /// If set, creates a stop limit order
    #[serde(rename = "limit_price", skip_serializing_if = "Option::is_none")]
    pub limit_price: Option<f64>,
    /// The trigger target that `stop_price` and `bracket_price` refer to.
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Target>,
    /// Trigger price
    #[serde(rename = "stop_price")]
    pub stop_price: f64,
    /// If set, creates a bracket order
    #[serde(rename = "bracket_price", skip_serializing_if = "Option::is_none")]
    pub bracket_price: Option<f64>,
    /// If set, creates a trailing stop order
    #[serde(
        rename = "trailing_stop_callback_rate",
        skip_serializing_if = "Option::is_none"
    )]
    pub trailing_stop_callback_rate: Option<f64>,
    /// Label will be set on the activated order
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Activated order will be reduce-only
    #[serde(rename = "reduce_only", skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
}

impl PrivateCreateConditionalOrderRequest {
    pub fn new(
        direction: Direction,
        instrument_name: String,
        amount: f64,
        stop_price: f64,
    ) -> PrivateCreateConditionalOrderRequest {
        PrivateCreateConditionalOrderRequest {
            direction,
            instrument_name,
            amount,
            limit_price: None,
            target: None,
            stop_price,
            bracket_price: None,
            trailing_stop_callback_rate: None,
            label: None,
            reduce_only: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Buy
    }
}
/// The trigger target that `stop_price` and `bracket_price` refer to.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Target {
    #[serde(rename = "last")]
    Last,
    #[serde(rename = "mark")]
    Mark,
    #[serde(rename = "index")]
    Index,
}

impl Default for Target {
    fn default() -> Target {
        Self::Last
    }
}
