/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateCancelBotRequest {
    /// The `bot_id` returned when creating the bot, or calling `private/bots`.
    #[serde(rename = "bot_id")]
    pub bot_id: String,
}

impl PrivateCancelBotRequest {
    pub fn new(bot_id: String) -> PrivateCancelBotRequest {
        PrivateCancelBotRequest { bot_id }
    }
}
