/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateAmendRequest {
    /// Exactly one of `client_order_id` or `order_id` must be specified.
    #[serde(rename = "client_order_id", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<i32>,
    /// Exactly one of `client_order_id` or `order_id` must be specified.
    #[serde(rename = "order_id", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
    #[serde(rename = "price")]
    pub price: f64,
    #[serde(rename = "amount")]
    pub amount: f64,
    /// If the instrument has a safety price collar set, and the new limit price is in cross with (more aggressive than) this collar, how to handle. If set to `ignore`, the amend will proceed as requested. If `reject`, the request fails early. If `clamp`, the price is adjusted to the collar.  The default is `reject`.
    #[serde(rename = "collar", skip_serializing_if = "Option::is_none")]
    pub collar: Option<Collar>,
}

impl PrivateAmendRequest {
    pub fn new(price: f64, amount: f64) -> PrivateAmendRequest {
        PrivateAmendRequest {
            client_order_id: None,
            order_id: None,
            price,
            amount,
            collar: None,
        }
    }
}
/// If the instrument has a safety price collar set, and the new limit price is in cross with (more aggressive than) this collar, how to handle. If set to `ignore`, the amend will proceed as requested. If `reject`, the request fails early. If `clamp`, the price is adjusted to the collar.  The default is `reject`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Collar {
    #[serde(rename = "ignore")]
    Ignore,
    #[serde(rename = "reject")]
    Reject,
    #[serde(rename = "clamp")]
    Clamp,
}

impl Default for Collar {
    fn default() -> Collar {
        Self::Ignore
    }
}
