/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateMmRfqAmendQuoteRequest {
    /// Exactly one of `client_order_id` or `order_id` must be specified.
    #[serde(rename = "client_order_id", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<i32>,
    /// Exactly one of `client_order_id` or `order_id` must be specified.
    #[serde(rename = "order_id", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
    /// Limit price for the quote (for one combination).
    #[serde(rename = "price")]
    pub price: f64,
    /// Number of combinations to quote. Anything over the requested amount will not be visible to the requester.
    #[serde(rename = "amount")]
    pub amount: f64,
}

impl PrivateMmRfqAmendQuoteRequest {
    pub fn new(price: f64, amount: f64) -> PrivateMmRfqAmendQuoteRequest {
        PrivateMmRfqAmendQuoteRequest {
            client_order_id: None,
            order_id: None,
            price,
            amount,
        }
    }
}
