/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrivateInsert {
    PrivateInsertResult(Box<models::OrderStatus>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for PrivateInsert {
    fn default() -> Self {
        Self::PrivateInsertResult(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderType {
    #[serde(rename = "limit")]
    Limit,
    #[serde(rename = "market")]
    Market,
}

impl Default for OrderType {
    fn default() -> OrderType {
        Self::Limit
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TimeInForce {
    #[serde(rename = "good_till_cancelled")]
    GoodTillCancelled,
    #[serde(rename = "immediate_or_cancel")]
    ImmediateOrCancel,
}

impl Default for TimeInForce {
    fn default() -> TimeInForce {
        Self::GoodTillCancelled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Buy
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "partially_filled")]
    PartiallyFilled,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "cancelled_partially_filled")]
    CancelledPartiallyFilled,
    #[serde(rename = "filled")]
    Filled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Open
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChangeReason {
    #[serde(rename = "existing")]
    Existing,
    #[serde(rename = "insert")]
    Insert,
    #[serde(rename = "amend")]
    Amend,
    #[serde(rename = "cancel")]
    Cancel,
    #[serde(rename = "fill")]
    Fill,
}

impl Default for ChangeReason {
    fn default() -> ChangeReason {
        Self::Existing
    }
}
/// Detailed reason of order deletion if the order was deleted, omitted otherwise.  The following reasons are possible:  - `client_cancel`: Order was cancelled by the client, e.g. with a call to `private/cancel`.  - `client_bulk_cancel`: Order was cancelled by the client with a bulk cancel call, e.g. `private/cancel_all`.  - `session_end`: Non-persistent order was automatically cancelled when a WebSocket session ended.  - `instrument_deactivated`: Order was automatically cancelled when the order instrument was deactivated,   for example after expiration.  - `mm_protection`: Order was automatically cancelled when configured market maker protection amount was exhausted.  - `failover`: Non-persistent order was automatically cancelled on matching engine failover.  - `margin_breach`: Order was automatically cancelled in a response to a margin breach on the account as part   of automatic liquidation procedures.  - `filled`: Order was filled in full.  - `immediate_cancel`: The order was submitted as \"immediate-or-cancel\" and was not filled in full immediately.   Note that the order might be partially filled when this delete reason is set.  - `admin_cancel`: The order was cancelled by an exchange admin.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeleteReason {
    #[serde(rename = "client_cancel")]
    ClientCancel,
    #[serde(rename = "client_bulk_cancel")]
    ClientBulkCancel,
    #[serde(rename = "session_end")]
    SessionEnd,
    #[serde(rename = "instrument_deactivated")]
    InstrumentDeactivated,
    #[serde(rename = "mm_protection")]
    MmProtection,
    #[serde(rename = "failover")]
    Failover,
    #[serde(rename = "margin_breach")]
    MarginBreach,
    #[serde(rename = "filled")]
    Filled,
    #[serde(rename = "immediate_cancel")]
    ImmediateCancel,
    #[serde(rename = "admin_cancel")]
    AdminCancel,
}

impl Default for DeleteReason {
    fn default() -> DeleteReason {
        Self::ClientCancel
    }
}
/// Detailed reason of order insertion.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InsertReason {
    #[serde(rename = "client_request")]
    ClientRequest,
    #[serde(rename = "conditional_order")]
    ConditionalOrder,
    #[serde(rename = "liquidation")]
    Liquidation,
}

impl Default for InsertReason {
    fn default() -> InsertReason {
        Self::ClientRequest
    }
}
