/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateMmRfqInsertQuoteRequest {
    /// The ID of the RFQ this quote is for.
    #[serde(rename = "rfq_id")]
    pub rfq_id: String,
    /// Session-local identifier for this order. Only valid for websocket sessions. If set, must be a number between 0 and 2^64-1, inclusive. When using numbers larger than 2^32, please beware of implicit floating point conversions in some JSON libraries.
    #[serde(rename = "client_order_id", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<i32>,
    /// The side of the quote.
    #[serde(rename = "direction")]
    pub direction: Direction,
    /// Limit price for the quote (for one combination).
    #[serde(rename = "price")]
    pub price: f64,
    /// Number of combinations to quote. Anything over the requested amount will not be visible to the requester.
    #[serde(rename = "amount")]
    pub amount: f64,
    /// A label to attach to eventual trades.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl PrivateMmRfqInsertQuoteRequest {
    pub fn new(
        rfq_id: String,
        direction: Direction,
        price: f64,
        amount: f64,
    ) -> PrivateMmRfqInsertQuoteRequest {
        PrivateMmRfqInsertQuoteRequest {
            rfq_id,
            client_order_id: None,
            direction,
            price,
            amount,
            label: None,
        }
    }
}
/// The side of the quote.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Buy
    }
}
