/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrivateCreateBotRequest {
    Sgsl(Box<models::Sgsl>),
    Ocq(Box<models::Ocq>),
    Levels(Box<models::Levels>),
    Grid(Box<models::Grid>),
    DHedge(Box<models::DHedge>),
    DFollow(Box<models::DFollow>),
}

impl Default for PrivateCreateBotRequest {
    fn default() -> Self {
        Self::Sgsl(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Signal {
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "mark")]
    Mark,
}

impl Default for Signal {
    fn default() -> Signal {
        Self::Index
    }
}
