/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicMarkPriceHistoricalDataInlinePropertiesMarkOneof0ItemsV6 {
    #[serde(rename = "v0")]
    pub v0: f64,
    #[serde(rename = "v1")]
    pub v1: f64,
    #[serde(rename = "v2")]
    pub v2: f64,
    #[serde(rename = "v3")]
    pub v3: f64,
}

impl PublicMarkPriceHistoricalDataInlinePropertiesMarkOneof0ItemsV6 {
    pub fn new(
        v0: f64,
        v1: f64,
        v2: f64,
        v3: f64,
    ) -> PublicMarkPriceHistoricalDataInlinePropertiesMarkOneof0ItemsV6 {
        PublicMarkPriceHistoricalDataInlinePropertiesMarkOneof0ItemsV6 { v0, v1, v2, v3 }
    }
}
