/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PublicIndexPriceHistoricalData {
    PublicIndexPriceHistoricalDataResult(Box<models::PublicIndexPriceHistoricalDataResult>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for PublicIndexPriceHistoricalData {
    fn default() -> Self {
        Self::PublicIndexPriceHistoricalDataResult(Default::default())
    }
}
