/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PublicMarkPriceHistoricalData {
    PublicMarkPriceHistoricalDataResult(Box<models::PublicMarkPriceHistoricalDataResult>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for PublicMarkPriceHistoricalData {
    fn default() -> Self {
        Self::PublicMarkPriceHistoricalDataResult(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InstrumentType {
    #[serde(rename = "perpetual")]
    Perpetual,
    #[serde(rename = "future")]
    Future,
    #[serde(rename = "combination")]
    Combination,
    #[serde(rename = "option")]
    Option,
}

impl Default for InstrumentType {
    fn default() -> InstrumentType {
        Self::Perpetual
    }
}
