/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicMarkPriceHistoricalDataInlinePropertiesMarkOneof0Items {
    #[serde(rename = "v0")]
    pub v0: f64,
    #[serde(rename = "v1")]
    pub v1: f64,
    #[serde(rename = "v2")]
    pub v2: f64,
    #[serde(rename = "v3")]
    pub v3: f64,
    #[serde(rename = "v4")]
    pub v4: f64,
    #[serde(rename = "v5")]
    pub v5: f64,
    #[serde(rename = "v6")]
    pub v6: Box<models::PublicMarkPriceHistoricalDataInlinePropertiesMarkOneof0ItemsV6>,
}

impl PublicMarkPriceHistoricalDataInlinePropertiesMarkOneof0Items {
    pub fn new(
        v0: f64,
        v1: f64,
        v2: f64,
        v3: f64,
        v4: f64,
        v5: f64,
        v6: models::PublicMarkPriceHistoricalDataInlinePropertiesMarkOneof0ItemsV6,
    ) -> PublicMarkPriceHistoricalDataInlinePropertiesMarkOneof0Items {
        PublicMarkPriceHistoricalDataInlinePropertiesMarkOneof0Items {
            v0,
            v1,
            v2,
            v3,
            v4,
            v5,
            v6: Box::new(v6),
        }
    }
}
