/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PublicSystemInfo {
    PublicSystemInfoResult(Box<models::PublicSystemInfoResult>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for PublicSystemInfo {
    fn default() -> Self {
        Self::PublicSystemInfoResult(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Environment {
    #[serde(rename = "testnet")]
    Testnet,
    #[serde(rename = "production")]
    Production,
}

impl Default for Environment {
    fn default() -> Environment {
        Self::Testnet
    }
}
