/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PublicInstrument {
    Instrument(Box<models::Instrument>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for PublicInstrument {
    fn default() -> Self {
        Self::Instrument(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "perpetual")]
    Perpetual,
    #[serde(rename = "future")]
    Future,
    #[serde(rename = "option")]
    Option,
    #[serde(rename = "combination")]
    Combination,
}

impl Default for Type {
    fn default() -> Type {
        Self::Perpetual
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OptionType {
    #[serde(rename = "call")]
    Call,
    #[serde(rename = "put")]
    Put,
}

impl Default for OptionType {
    fn default() -> OptionType {
        Self::Call
    }
}
