/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Removed {
    #[serde(rename = "removed")]
    pub removed: models::Instrument,
}

impl Removed {
    pub fn new(removed: models::Instrument) -> Removed {
        Removed { removed }
    }
}
