/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequiredMarginForOrderParamsLegsInner {
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    /// Quantity for this leg. May be negative.
    #[serde(rename = "quantity")]
    pub quantity: rust_decimal::Decimal,
}

impl RequiredMarginForOrderParamsLegsInner {
    pub fn new(
        instrument_name: String,
        quantity: rust_decimal::Decimal,
    ) -> RequiredMarginForOrderParamsLegsInner {
        RequiredMarginForOrderParamsLegsInner {
            instrument_name,
            quantity,
        }
    }
}
