/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResolutionEnum {
    #[serde(rename = "1d")]
    Variant1d,
    #[serde(rename = "1w")]
    Variant1w,
    #[serde(rename = "1mo")]
    Variant1mo,
}

impl std::fmt::Display for ResolutionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant1d => write!(f, "1d"),
            Self::Variant1w => write!(f, "1w"),
            Self::Variant1mo => write!(f, "1mo"),
        }
    }
}

impl Default for ResolutionEnum {
    fn default() -> ResolutionEnum {
        Self::Variant1d
    }
}
