/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RfqInsertReasonEnum {
    #[serde(rename = "client_request")]
    ClientRequest,
    #[serde(rename = "liquidation")]
    Liquidation,
}

impl std::fmt::Display for RfqInsertReasonEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ClientRequest => write!(f, "client_request"),
            Self::Liquidation => write!(f, "liquidation"),
        }
    }
}

impl Default for RfqInsertReasonEnum {
    fn default() -> RfqInsertReasonEnum {
        Self::ClientRequest
    }
}
