/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RfqOrder {
    /// Identifier of the RFQ.
    #[serde(rename = "rfq_id")]
    pub rfq_id: String,
    /// Identifier of the individual quote.
    #[serde(rename = "order_id")]
    pub order_id: String,
    /// Client-supplied order id. Field is omitted if no client order id was supplied.
    #[serde(rename = "client_order_id", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<f64>,
    #[serde(rename = "direction")]
    pub direction: Direction,
    #[serde(rename = "price")]
    pub price: f64,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// the price at which this order traded.
    #[serde(rename = "trade_price", skip_serializing_if = "Option::is_none")]
    pub trade_price: Option<f64>,
    /// the number of combinations that traded.
    #[serde(rename = "trade_amount", skip_serializing_if = "Option::is_none")]
    pub trade_amount: Option<f64>,
    /// Detailed reason of order deletion.
    #[serde(rename = "delete_reason", skip_serializing_if = "Option::is_none")]
    pub delete_reason: Option<DeleteReason>,
    /// This field is set only on subscriptions.
    #[serde(rename = "event", skip_serializing_if = "Option::is_none")]
    pub event: Option<Event>,
}

impl RfqOrder {
    pub fn new(
        rfq_id: String,
        order_id: String,
        direction: Direction,
        price: f64,
        amount: f64,
    ) -> RfqOrder {
        RfqOrder {
            rfq_id,
            order_id,
            client_order_id: None,
            direction,
            price,
            amount,
            label: None,
            trade_price: None,
            trade_amount: None,
            delete_reason: None,
            event: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Buy
    }
}
/// Detailed reason of order deletion.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeleteReason {
    #[serde(rename = "client_cancel")]
    ClientCancel,
    #[serde(rename = "session_end")]
    SessionEnd,
    #[serde(rename = "instrument_deactivated")]
    InstrumentDeactivated,
    #[serde(rename = "mm_protection")]
    MmProtection,
    #[serde(rename = "failover")]
    Failover,
    #[serde(rename = "margin_breach")]
    MarginBreach,
    #[serde(rename = "filled")]
    Filled,
}

impl Default for DeleteReason {
    fn default() -> DeleteReason {
        Self::ClientCancel
    }
}
/// This field is set only on subscriptions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "Inserted")]
    Inserted,
    #[serde(rename = "Amended")]
    Amended,
    #[serde(rename = "Cancelled")]
    Cancelled,
    #[serde(rename = "Filled")]
    Filled,
    #[serde(rename = "Existing")]
    Existing,
}

impl Default for Event {
    fn default() -> Event {
        Self::Inserted
    }
}
