/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RfqEventEnum {
    #[serde(rename = "Created")]
    Created,
    #[serde(rename = "Cancelled")]
    Cancelled,
    #[serde(rename = "Traded")]
    Traded,
    #[serde(rename = "Existing")]
    Existing,
}

impl std::fmt::Display for RfqEventEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Created => write!(f, "Created"),
            Self::Cancelled => write!(f, "Cancelled"),
            Self::Traded => write!(f, "Traded"),
            Self::Existing => write!(f, "Existing"),
        }
    }
}

impl Default for RfqEventEnum {
    fn default() -> RfqEventEnum {
        Self::Created
    }
}
