/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RfqQuotedBid : The bid price/amount quoted so far, if any. Visible only to the requester.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RfqQuotedBid {
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
}

impl RfqQuotedBid {
    /// The bid price/amount quoted so far, if any. Visible only to the requester.
    pub fn new() -> RfqQuotedBid {
        RfqQuotedBid {
            price: None,
            amount: None,
        }
    }
}
