/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RfqDeleteReasonEnum {
    #[serde(rename = "client_cancel")]
    ClientCancel,
    #[serde(rename = "filled")]
    Filled,
}

impl std::fmt::Display for RfqDeleteReasonEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ClientCancel => write!(f, "client_cancel"),
            Self::Filled => write!(f, "filled"),
        }
    }
}

impl Default for RfqDeleteReasonEnum {
    fn default() -> RfqDeleteReasonEnum {
        Self::ClientCancel
    }
}
