/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcErrorResponse {
    /// Your request id, or null if not supplied.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<serde_json::Value>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::ErrorResponseError>>,
}

impl RpcErrorResponse {
    pub fn new() -> RpcErrorResponse {
        RpcErrorResponse {
            id: None,
            error: None,
        }
    }
}
