/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionNotification {
    /// Channel name as in subscription.
    #[serde(rename = "channel_name")]
    pub channel_name: String,
    #[serde(rename = "notification")]
    pub notification: models::Session,
}

impl SessionNotification {
    pub fn new(channel_name: String, notification: models::Session) -> SessionNotification {
        SessionNotification {
            channel_name,
            notification,
        }
    }
}
