/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetCancelOnDisconnectParams {
    /// Heartbeat interval
    #[serde(rename = "timeout_secs")]
    pub timeout_secs: i32,
}

impl SetCancelOnDisconnectParams {
    pub fn new(timeout_secs: i32) -> SetCancelOnDisconnectParams {
        SetCancelOnDisconnectParams { timeout_secs }
    }
}
