/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SingleLevelQuote : bid quote
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SingleLevelQuote {
    /// Limit price.
    #[serde(rename = "p")]
    pub p: rust_decimal::Decimal,
    /// Amount; set to zero to delete quote.
    #[serde(rename = "a")]
    pub a: rust_decimal::Decimal,
}

impl SingleLevelQuote {
    /// bid quote
    pub fn new(p: rust_decimal::Decimal, a: rust_decimal::Decimal) -> SingleLevelQuote {
        SingleLevelQuote { p, a }
    }
}
