/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StpActionEnum {
    #[serde(rename = "cancel_aggressive_partial_fill")]
    CancelAggressivePartialFill,
    #[serde(rename = "cancel_aggressive_no_fill")]
    CancelAggressiveNoFill,
}

impl std::fmt::Display for StpActionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CancelAggressivePartialFill => write!(f, "cancel_aggressive_partial_fill"),
            Self::CancelAggressiveNoFill => write!(f, "cancel_aggressive_no_fill"),
        }
    }
}

impl Default for StpActionEnum {
    fn default() -> StpActionEnum {
        Self::CancelAggressivePartialFill
    }
}
