/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StpLevelEnum {
    #[serde(rename = "customer")]
    Customer,
    #[serde(rename = "account")]
    Account,
    #[serde(rename = "disabled")]
    Disabled,
}

impl std::fmt::Display for StpLevelEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Customer => write!(f, "customer"),
            Self::Account => write!(f, "account"),
            Self::Disabled => write!(f, "disabled"),
        }
    }
}

impl Default for StpLevelEnum {
    fn default() -> StpLevelEnum {
        Self::Customer
    }
}
