/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TargetEnum {
    #[serde(rename = "last")]
    Last,
    #[serde(rename = "mark")]
    Mark,
    #[serde(rename = "index")]
    Index,
}

impl std::fmt::Display for TargetEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Last => write!(f, "last"),
            Self::Mark => write!(f, "mark"),
            Self::Index => write!(f, "index"),
        }
    }
}

impl Default for TargetEnum {
    fn default() -> TargetEnum {
        Self::Last
    }
}
