/*
 * Ticker Feed Schemas
 *
 * Schema definitions for ticker feed data types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TickerData {
    /// Price of the best (highest) bid in the orderbook, or null if empty
    #[serde(rename = "best_bid_price", skip_serializing_if = "Option::is_none")]
    pub best_bid_price: Option<f64>,
    /// Size of best bid, or null if orderbook is empty
    #[serde(rename = "best_bid_amount", skip_serializing_if = "Option::is_none")]
    pub best_bid_amount: Option<f64>,
    /// Price of best (lowest) ask in the orderbook, or null if empty
    #[serde(rename = "best_ask_price", skip_serializing_if = "Option::is_none")]
    pub best_ask_price: Option<f64>,
    /// Size of best ask, or null if orderbook is empty
    #[serde(rename = "best_ask_amount", skip_serializing_if = "Option::is_none")]
    pub best_ask_amount: Option<f64>,
    /// Price of last trade, or null if no trades registered. Not included for combinations.
    #[serde(rename = "last_price", skip_serializing_if = "Option::is_none")]
    pub last_price: Option<f64>,
    /// Current mark price
    #[serde(rename = "mark_price")]
    pub mark_price: f64,
    /// Unix timestamp when the price was marked
    #[serde(rename = "mark_timestamp")]
    pub mark_timestamp: f64,
    /// Implied volatility calculated at time of marking. Only included for options, not combinations.
    #[serde(rename = "iv", skip_serializing_if = "Option::is_none")]
    pub iv: Option<f64>,
    /// Delta calculated at time of marking. Not included for combinations.
    #[serde(rename = "delta", skip_serializing_if = "Option::is_none")]
    pub delta: Option<f64>,
    /// Index price at time of marking
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<f64>,
    /// Forward price at time of marking. Only included for options.
    #[serde(rename = "forward", skip_serializing_if = "Option::is_none")]
    pub forward: Option<f64>,
    /// Total volume traded over the last 24 hours. Not included for combinations.
    #[serde(rename = "volume_24h", skip_serializing_if = "Option::is_none")]
    pub volume_24h: Option<f64>,
    /// Total value traded over the last 24 hours. Not included for combinations.
    #[serde(rename = "value_24h", skip_serializing_if = "Option::is_none")]
    pub value_24h: Option<f64>,
    /// Lowest price in the last 24 hours. Not included for combinations.
    #[serde(rename = "low_price_24h", skip_serializing_if = "Option::is_none")]
    pub low_price_24h: Option<f64>,
    /// Highest price in the last 24 hours. Not included for combinations.
    #[serde(rename = "high_price_24h", skip_serializing_if = "Option::is_none")]
    pub high_price_24h: Option<f64>,
    /// Difference in price between first and last trades in last 24h, null if no trades. Not included for combinations.
    #[serde(rename = "change_24h", skip_serializing_if = "Option::is_none")]
    pub change_24h: Option<f64>,
    /// Current price collar low (checks new asks)
    #[serde(rename = "collar_low", skip_serializing_if = "Option::is_none")]
    pub collar_low: Option<f64>,
    /// Current price collar high (checks new bids)
    #[serde(rename = "collar_high", skip_serializing_if = "Option::is_none")]
    pub collar_high: Option<f64>,
    /// Total number of outstanding unsettled contracts. Not included for combinations.
    #[serde(rename = "open_interest", skip_serializing_if = "Option::is_none")]
    pub open_interest: Option<f64>,
    /// Current rate at which long position pays and short position earns. Only included for perpetuals.
    #[serde(rename = "funding_rate", skip_serializing_if = "Option::is_none")]
    pub funding_rate: Option<f64>,
    /// Funding value of a single contract long position since last settlement. Only included for perpetuals.
    #[serde(rename = "funding_mark", skip_serializing_if = "Option::is_none")]
    pub funding_mark: Option<f64>,
    /// Total funding accumulated for a single contract long position over the last 24 hours. Only included for perpetuals.
    #[serde(
        rename = "realised_funding_24h",
        skip_serializing_if = "Option::is_none"
    )]
    pub realised_funding_24h: Option<f64>,
    /// Average funding rate for the last 24 hours. Only included for perpetuals.
    #[serde(
        rename = "average_funding_rate_24h",
        skip_serializing_if = "Option::is_none"
    )]
    pub average_funding_rate_24h: Option<f64>,
}

impl TickerData {
    pub fn new(mark_price: f64, mark_timestamp: f64) -> TickerData {
        TickerData {
            best_bid_price: None,
            best_bid_amount: None,
            best_ask_price: None,
            best_ask_amount: None,
            last_price: None,
            mark_price,
            mark_timestamp,
            iv: None,
            delta: None,
            index: None,
            forward: None,
            volume_24h: None,
            value_24h: None,
            low_price_24h: None,
            high_price_24h: None,
            change_24h: None,
            collar_low: None,
            collar_high: None,
            open_interest: None,
            funding_rate: None,
            funding_mark: None,
            realised_funding_24h: None,
            average_funding_rate_24h: None,
        }
    }
}
