/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TimeInForceEnum {
    #[serde(rename = "good_till_cancelled")]
    GoodTillCancelled,
    #[serde(rename = "immediate_or_cancel")]
    ImmediateOrCancel,
}

impl std::fmt::Display for TimeInForceEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GoodTillCancelled => write!(f, "good_till_cancelled"),
            Self::ImmediateOrCancel => write!(f, "immediate_or_cancel"),
        }
    }
}

impl Default for TimeInForceEnum {
    fn default() -> TimeInForceEnum {
        Self::GoodTillCancelled
    }
}
