/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyInternalTransferParamsPositionsInner {
    /// Instrument feedcode.
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    /// Amount to transfer. Use a negative value to transfer in reverse direction.
    #[serde(rename = "amount")]
    pub amount: rust_decimal::Decimal,
}

impl VerifyInternalTransferParamsPositionsInner {
    pub fn new(
        instrument_name: String,
        amount: rust_decimal::Decimal,
    ) -> VerifyInternalTransferParamsPositionsInner {
        VerifyInternalTransferParamsPositionsInner {
            instrument_name,
            amount,
        }
    }
}
